server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
  port: 8080

spring:
  application:
    name: student-management-system
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/StudentManagement
    username: kacper
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    user: guest
    password: guest
    host: localhost
    port: 5672
  mail:
    host: smtp.gmail.com
    port: 587
    username: studentmanagementsystem23@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


